HOPE_OBJECT_ID_TO_NAME = {"1": "AlphabetSoup",
    "2": "BBQSauce",
    "3": "Butter",
    "4": "Cherries",
    "5": "ChocolatePudding",
    "6": "Cookies",
    "7": "Corn",
    "8": "CreamCheese",
    "9": "GranolaBars",
    "10": "GreenBeans",
    "11": "Ketchup",
    "12": "MacaroniAndCheese",
    "13": "Mayo",
    "14": "Milk",
    "15": "Mushrooms",
    "16": "Mustard",
    "17": "OrangeJuice",
    "18": "Parmesan",
    "19": "Peaches",
    "20": "PeasAndCarrots",
    "21": "Pineapple",
    "22": "Popcorn",
    "23": "Raisins",
    "24": "SaladDressing",
    "25": "Spaghetti",
    "26": "TomatoSauce",
    "27": "Tuna",
    "28": "Yogurt"}

HOPE_OBJECT_NAME_TO_ID = {v:k for k,v in HOPE_OBJECT_ID_TO_NAME.items()}